[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
reqwasm = "0.5.0"
wasm-bindgen-futures = "0.4.32"
futures = "0.3.21"
web-sys = "0.3.59"
log = "0.4.17"
console_log = "0.2.0"